
export default function DougReference() {
    return (
        <main className="pageBodyContainer">
            <div id="bio" className="contentFade w-screen flex flex-row justify-center items-start bg-black bg-opacity-65" >
                <div className="h-full backdrop-blur-sm flex flex-col">
                    <div className="py-64 px-8 text-center flex flex-col justify-center h-[80vh] lg:h-[90vh]">
                        <h1 className="text-6xl sm:text-8xl mb-6 font-semibold w-full py-2"><span className="text-transparent bg-clip-text titleFade text-center">{`Doug McLiechey`}</span></h1>
                        <h4 className="text-xl sm:text-2xl font-extralight mb-16 text-white contentFade">{`Chief Technology Officer of Creative Path Solutions`}</h4>
                    </div>
                    <div className="pb-16 contentFade h-[10vh]" >
                        <p className="text-sm italic text-white text-center px-12">{`Below is the content of Doug's letter. You can `}<a href="https://api.deandivizio.com/wp-content/uploads/2024/11/DeanDivizio_RecLetter_fromDougMcLiechey.pdf" target="_blank" className="underline text-blue">view/download the signed PDF here.</a></p>
                    </div>
                    <div className="px-12 py-8">
                        <p className="text-white text-xl font-extralight tracking-wider leading-relaxed mb-6">{`To Whom It May Concern,`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`My name is Doug McLiechey. I'm the Chief Technology Officer of Creative Path Solutions and have known Dean for the better part of a decade. `}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`To save you some time and summarize, Dean is tenacious, well spoken (and written), and lives and breathes all things related to technology. That last point is particularly true when it comes to web development, and solving real-world, practical problems with technology. `}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`We initially hired Dean as a graphic designer, with responsibilities ranging from designing newsletters to building and maintaining Wordpress sites. In the few months before he was hired, both our previous designer and our web specialist had left the company. In a lot of ways, Dean was thrown to wolves on day one. He stepped up and met the challenge, taking over multiple projects left from previous team members and assisting in client communications, while still completing all his necessary onboarding training requirements. A few weeks in, Dean noticed some of our sites weren't performing as expected. On his own initiative, he worked with our infra provider to diagnose the problems (including some things that went unnoticed by our previous web specialist), spec out reasonable horizontal and vertical scaling solutions, put them in a report, and delivered it to the C-suite along with his recommendations. After we made our decision on a path forward, Dean spearheaded the implementation of his proposed solution, alongside all his other responsibilities - with zero downtime for the client sites.`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`Dean has a great command over language. This is noticeable every time he speaks, but is particularly impactful in his writing. Throughout his time with CPS, Dean spent a lot of time training team members both in face-to-face settings as well as vicariously through creating and updating our internal documentation. He lead the charge in transitioning our content development from being entirely outsourced, to a mix of in house team members and AI - and to that end, wrote all of our documentation on safe but effective AI use. He then trained all the relevant team members on how to use AI in combination with our research tools to deliver content that hit SEO targets without sounding AI generated.`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`More than anything else, it's evident to me (and everyone else in his orbit) that Dean loves solving problems through technology. There are almost too many examples of this to list but here are two notable ones. `}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`When he decided our SEO auditing process required more manual work than he felt was reasonable, Dean decided to change that. He told me he felt like the bulk of the inefficiency came from a lack of standardization. He started with an Excel template to test his theory, then followed that up with a Mac app that team members could use to standardize the information collected in the audit as well as the format it was presented in. That app could then generate a CSV alongside a Word document with all the information. It wound up being an incredibly effective solution that allowed work to be split up between team members, then delivered to Dean for the final report - in about half the time as it had taken previously.`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`When we were experimenting with reusing components from existing Wordpress sites, we ran into an issue where the search and replace plugin wouldn't change anything on the front end, only the database. I was in the room the first - and only - time Dean had to go in and change things by hand. Before the end of the day, we had a Python script that automated the whole process `}<span className="italic mr-1">{`better `}</span> {` than the original search and replace plugin did. That was fun to watch.`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-12">{`All that to say, I can confidently recommend Dean for any position he's interested in - especially in a technical capacity. I truly believe he'll be an asset for any team he's on.`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-6">{`Sincerely,`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-0">{`Doug McLiechey`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-relaxed mb-0">{`Chief Technology Officer`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide leading-loose mb-0">{`Creative Path Solutions`}</p>
                        <p className="text-white text-xl font-extralight tracking-wide underline leading-loose mb-0"><a href="tel:5179274512">{`(517) 927-4512`}</a></p>
                    </div>
                </div>
            </div>
        </main>
    );
}
